### ISSUE TITLE
Dominant seventh from G doesn’t work

### ISSUE THREAD

**Issue by maximal** [stewdio/beep.js#5]
Trying to press a dominant seventh chord from G: G—B—D—F.

In the combination of `B` + `M` + `W` + `R` last pressed key doesn’t sound.

When trying `B` + `M` + `W` + `T` (magor triad G—B—D—G), all is just fine.

Chromium  41.0.2272.76
Ubuntu Linux 14.10 (64-bit)

**Comment by stewdio** [comment]
Hi Maximal. Thanks for your interest! I’m experiencing the same in Chrome 41 for OS X 10.10.2, but my suspicion is that it’s a hardware limitation of keyboards rather a software bug. In addition to the key combination you’ve mentioned I’ve found others—pretty much by randomly mashing down as many keys as I can at once ;) I doubt keyboards were designed to reliably transmit many keypresses simultaneously as this isn’t necessary to support regular typing. 

Meanwhile, scripting (rather than key-pressing) the simultaneous activation of those four Triggers you mentioned works as expected as does key-pressing `B`+`M`+`W` and mousing over the final Trigger. Can anyone confirm that this is a hardware thing? Either way, solutions appreciated!

**Comment by rojaro** [comment]
http://en.wikipedia.org/wiki/Rollover_%28key%29#n-key_rollover

**Comment by stewdio** [comment]
I’m going to accept @rojaro’s [n-key rollover](http://en.wikipedia.org/wiki/Rollover_%28key%29#n-key_rollover) link as nearly-proof that it’s a hardware limitation and close this issue. (Flimsy as a proof, I know, but we’re not designing space rockets here!)
